In [136]:
import requests as rq
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np

In [143]:
titulos = []
anos = []
edades = []
duraciones = []
generos = []
ratings = []
directores = []
votos = []
ganancias = []
for i in range (10):
    num = i*100 + 1
    url = f"https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=100&start={num}&ref_=adv_nxt"
    r = rq.get(url)
    sopa = bs(r.content, "html.parser")
    lista_pelis = sopa.find_all('div', class_='lister-item mode-advanced')

    for data in lista_pelis:

        contenido = data.find('div', class_='lister-item-content')
        cabecera = contenido.find('h3')
        titulo = cabecera.find('a')
        ano = cabecera.find('span', class_='lister-item-year text-muted unbold')
        ano = ano.text.replace('(', '')
        ano = ano.replace(')', '')
        titulos.append(titulo.text)
        anos.append(ano)
        
        cuerpo = contenido.find('p')
        edad = cuerpo.find('span', class_= 'certificate')
        tiempo = cuerpo.find('span', class_ = 'runtime')
        genero = cuerpo.find('span', class_= 'genre')
        if edad:
            edades.append(edad.text)
        else:
            edades.append(0)
        duraciones.append(tiempo.text)
        generos.append(genero.text.strip())

        cuerpo2 = contenido.find('div', class_= 'ratings-bar')
        rating = cuerpo2.find('div', class_='inline-block ratings-imdb-rating')
        ratings.append(rating.text.strip())

        pie = contenido.find('p', class_='')
        pie = pie.text.strip().split('|')
        director = pie[0]
        director = director.split('\n')
        directores.append(director[1])

        pie2 = contenido.find('p', class_='sort-num_votes-visible')
        pie2 = pie2.text.strip().split('|')
        voto = pie2[0].split(':')
        voto = voto[1].strip()
        voto = voto.replace(',', '')
        if len(pie2) == 3:
            precio = pie2[1].split(':')
            precio = precio[1].strip()
        else:
            precio = np.nan
        votos.append(voto)
        ganancias.append(precio)

In [144]:
df_pelis = pd.DataFrame()
df_pelis['Titulo'] = titulos
df_pelis['Ano'] = anos
df_pelis['Edad_min'] = edades
df_pelis['duraciones'] = duraciones
df_pelis['Genero'] = generos
df_pelis['Rating'] = ratings
df_pelis['Director'] = directores
df_pelis['Votos'] = votos
df_pelis['Ganancias'] = ganancias
df_pelis

,Titulo,Ano,Edad_min,duraciones,Genero,Rating,Director,Votos,Ganancias
0,Sueños de Libertad,1994,18,142 min,Drama,9.3,Frank Darabont,2663585,$28.34M
1,El padrino,1972,0,175 min,"Crime, Drama",9.2,Francis Ford Coppola,1845856,$134.97M
2,Kantara,2022,0,148 min,"Action, Adventure, Drama",9.0,Rishab Shetty,68158,NaN
3,The Dark Knight,2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,2636571,$534.86M
4,The Lord of the Rings: The Return of the King,2003,PG-13,201 min,"Action, Adventure, Drama",9.0,Peter Jackson,1836409,$377.85M
...,...,...,...,...,...,...,...,...,...
995,Sabrina,1954,0,113 min,"Comedy, Drama, Romance",7.6,Billy Wilder,65716,NaN
996,From Here to Eternity,1953,0,118 min,"Drama, Romance, War",7.6,Fred Zinnemann,47498,NaN
997,Snow White and the Seven Dwarfs,1937,Approved,83 min,"Animation, Adventure, Family",7.6,"William Cottrell,",200412,NaN
998,The 39 Steps,1935,0,86 min,"Crime, Mystery, Thriller",7.6,Alfred Hitchcock,57618,NaN
999,El hombre invisible,1933,0,71 min,"Horror, Sci-Fi",7.6,James Whale,36209,NaN

In [139]:
df_pelis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Titulo      1000 non-null   object
 1   Ano         1000 non-null   object
 2   Edad_min    608 non-null    object
 3   duraciones  1000 non-null   object
 4   Genero      1000 non-null   object
 5   Rating      1000 non-null   object
 6   Director    1000 non-null   object
 7   Votos       1000 non-null   object
 8   Ganancias   220 non-null    object
dtypes: object(9)
memory usage: 70.4+ KB

In [146]:
edad_nan = df_pelis[df_pelis["Edad_min"] == 0]
edad_nan[100]

KeyError: 100